language: python

python:
  - '3.6'

branches:
  only:
    - master

install:
  - sudo apt-get update

  - python setup.py test
  - python setup.py install

script:
  - coverage run --branch --source= setup.py test

after_success:
  - coveralls